#配置端口
server:
  port: 8088

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus_join?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    #username: {username} password: {password}
    username: root
    password: 123456

#mybatisplus配置
mybatis-plus:
  configuration:
    #日志输出配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #不输出日志信息
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
##MyBatis-Plus相关配置
#mybatis-plus:
#  configuration:
#    #配置日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.tang.mybatisplusjoin.pojo
#  type-enums-package: com.tang.mybatisplusjoin.enums